---
# tasks file for asg

- name: create launch config
  ec2_lc:
    name: "{{ lc_name }}"
    image_id: "{{ image_id }}"
    key_name: "{{ key_name }}"
    region: "{{ region }}"
    security_groups: "{{ lc_security_groups }}"
    instance_type: "{{ instance_type }}"
    instance_profile_name: "{{ instance_profile_name }}"
    assign_public_ip: no
  tags: launch_config

- name: create autoscale groups
  ec2_asg:
    name: "{{ asg_group_name }}"
    health_check_period: 60
    load_balancers: "{{ load_balancers }}"
    health_check_type: EC2
    availability_zones: "{{ availability_zones }}"
    launch_config_name: "{{ lc_name }}"
    min_size: "{{ asg_min_size }}"
    max_size: "{{ asg_max_size }}"
    desired_capacity: "{{ asg_desired_capacity }}"
    region: "{{ region }}"
    replace_all_instances: yes
    vpc_zone_identifier: "{{ asg_subnets }}"
    tags:
      - Name: "notes-{{env}}-web"
        propagate_at_launch: yes
      - Environment: "{{ env }}"
        propagate_at_launch: yes
      - ConfigVersion: "{{ config_version }}"
        propagate_at_launch: yes
    wait_for_instances: yes
  #until: asg_result.viable_instances|int >= asg_desired_capacity|int
  delay: 10
  retries: 120
  register: asg_result
