---
lc_suffix: "{{ image_id }}_{{ ansible_date_time.epoch }}"
lc_name: notes-web_{{ lc_suffix }}
key_name: xgs-keypair
region: eu-west-1
instance_type: t2.small
instance_profile_name: notes-web

asg_group_name: notes-web
asg_min_size: 3
asg_max_size: 6
asg_desired_capacity: 3
